Workly/Controllers/InterestedJobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Workly.Controllers
{
    public class InterestedJobsController : Controller
    {
        // GET: InterestedJobs
        public ActionResult Index()
        {
            return View();
        }
    }
}

Workly/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Workly.Models;

namespace Workly.Controllers
{
    public class UsersController : Controller
    {
        private JobSystemContext db = new JobSystemContext();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.WorklyUsers.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorklyUser worklyUser = db.WorklyUsers.Find(id);
            if (worklyUser == null)
            {
                return HttpNotFound();
            }
            worklyUser.ReviewList = db.Review.Where(u => u.Email==worklyUser.Email).ToList<Review>();
            return View(worklyUser);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorklyUser worklyUser = db.WorklyUsers.Find(id);
            if (worklyUser == null)
            {
                return HttpNotFound();
            }
            return View(worklyUser);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "WorklyUserId,Email,Rating, Review")] WorklyUser worklyUser)
        {
            var review = new Review();
            review.ReviewId = worklyUser.WorklyUserId;
            review.Email = worklyUser.Email;
            review.Comment = worklyUser.Review.Comment;
            db.Review.Add(review);
            var user = db.WorklyUsers.Find(worklyUser.WorklyUserId);
            int a = worklyUser.Rating.Rate;
            user.Rating.Sum += worklyUser.Rating.Rate;
            user.Rating.Times++;
            user.Rating.Average =user.Rating.Sum / user.Rating.Times;

            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(worklyUser);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Workly/Controllers/YourJobsController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Workly.Dtos;
using Workly.Models;

namespace Workly.Controllers
{
    public class YourJobsController : Controller
    {
        private JobSystemContext db = new JobSystemContext();
        [Authorize(Roles ="Employer")]
        public ActionResult Index()
        {
            string id = User.Identity.GetUserId();
            var yourList = from job in db.Jobs
                           where job.UserId == id
                           select job;
            return View(yourList);
        }

        // GET: YouJob/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: YouJob/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: YouJob/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,Name,Surname,Phone,Work,Field,Start,Locality,Salary,Duration")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(job);
        }

        // GET: YouJob/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: YouJob/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,Name,Surname,Phone,Work,Field,Start,Locality,Salary,Duration")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(job);
        }

        // GET: YouJob/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: YouJob/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Workly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <img src="https://cdn0.iconfinder.com/data/icons/thin-analytics/24/thin-0394_business_handshake_deal_contract_sign-512.png" alt="Site Logo" style="height:30px; width: 30px" />
                </a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WORKLY", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">   
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    @if (User.IsInRole("Employee") || User.IsInRole("Employer"))
                    {
                        <li>@Html.ActionLink("TOP", "Index", "Users")</li>
                        <li>@Html.ActionLink("Jobs", "Index", "Jobs")</li>
                    }
                    @if (User.IsInRole("Employee"))
                    {
                        <li>@Html.ActionLink("Interested jobs", "Index", "InterestedJobs")</li>
                    }
                    @if (User.IsInRole("Employer"))
                    {
                        <li>@Html.ActionLink("Your jobs", "Index", "YourJobs")</li>
                    }
                  
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - VMMM</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>